# Project: 实验4
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = as05_utility.o as05_district.o
LINKOBJ  = as05_utility.o as05_district.o
LIBS     = -L"H:/Dev C++/Dev-Cpp/MinGW64/lib" -L"H:/Dev C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"H:/Dev C++/Dev-Cpp/MinGW64/include" -I"H:/Dev C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"H:/Dev C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"H:/Dev C++/Dev-Cpp/MinGW64/include" -I"H:/Dev C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"H:/Dev C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"H:/Dev C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 实验4.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

as05_utility.o: as05_utility.c
	$(CC) -c as05_utility.c -o as05_utility.o $(CFLAGS)

as05_district.o: as05_district.c
	$(CC) -c as05_district.c -o as05_district.o $(CFLAGS)
