# Project: gobang
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o judgement.o
LINKOBJ  = main.o judgement.o
LIBS     = -L"H:/Dev C++/Dev-Cpp/MinGW64/lib" -L"H:/Dev C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"H:/Dev C++/Dev-Cpp/MinGW64/include" -I"H:/Dev C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"H:/Dev C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"H:/Dev C++/Dev-Cpp/MinGW64/include" -I"H:/Dev C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"H:/Dev C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"H:/Dev C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = gobang.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

judgement.o: judgement.c
	$(CC) -c judgement.c -o judgement.o $(CFLAGS)
