# Project: gobang
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = ai_algo.o controller.o eval_board.o main_game.o main.o
LINKOBJ  = ai_algo.o controller.o eval_board.o main_game.o main.o
LIBS     = -L"D:/Program/Dev-Cpp/MinGW64/lib" -L"D:/Program/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/Program/Dev-Cpp/MinGW64/include" -I"D:/Program/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Program/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/Program/Dev-Cpp/MinGW64/include" -I"D:/Program/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Program/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Program/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = gobang.exe
CXXFLAGS = $(CXXINCS) -fexec-charset=GBK -finput-charset=UTF-8
CFLAGS   = $(INCS) -fexec-charset=GBK -finput-charset=UTF-8
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

ai_algo.o: ai_algo.c
	$(CC) -c ai_algo.c -o ai_algo.o $(CFLAGS)

controller.o: controller.c
	$(CC) -c controller.c -o controller.o $(CFLAGS)

eval_board.o: eval_board.c
	$(CC) -c eval_board.c -o eval_board.o $(CFLAGS)

main_game.o: main_game.c
	$(CC) -c main_game.c -o main_game.o $(CFLAGS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)
